apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: dice-prom
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Tempo
    type: tempo
    uid: dice-tempo
    access: proxy
    url: http://tempo:3200
    editable: false
